# Generated by Django 5.2.11 on 2026-02-07 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (7-15 digits, optional leading +).", regex="^\\+?\\d{7,15}$"
                    )
                ],
            ),
        ),
    ]
